default:
  
  # Site name appears at the top of every page
  site_name: "Милеведент"
  site_name_en: "Milevedent"
  
  # Application link at the footer of each page
  app_name: "Bree"
  app_link: "http://adammiribyan.com/bree"
  
  # Admin
  admin_email: "adam.miribyan@gmail.com"